num1 = int(input("Enter the number 1: "))
num2 = int(input("Enter the number 2: "))
print("The sum is",num1 + num2)
print("The difference is",num1 - num2)
print("The product is",num1 * num2)
print("The quotient of division is",num1 / num2)
print("The quotient of floor division is",num1 // num2)
print("The remainder is",num1 % num2)
print(num1,"raised to the power of",num2,"is",num1 ** num2)
